disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - large_tuple

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - AniTripTests/*

line_length: 160
